services:
  - type: web
    name: txt-to-video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
      - key: API_HASH
      - key: BOT_TOKEN